spring:

  # H2
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # h2
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username:
#    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      database: mysql
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#cloud:
#  aws:
#    s3:
#      bucket: ${S3_BUCKET_NAME}
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_ID}
#      secret-key: ${AWS_SECRET_ACCESS_KEY}
#    region:
#      static: ${S3_REGION}
#      auto: false
#    stack:
#      auto: false
#logging:
#  level:
#    com:
#      amazonaws:
#        util:
#          EC2MetadataUtils: ERROR

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

